version: "3"

services:

  db:
    restart: always
    image: postgres:9.6
    ports:
        - "5433:5432"
    environment:
        POSTGRES_USER: gofant
        POSTGRES_DB: gofant
    volumes:
      - ./database/01_users.sql:/docker-entrypoint-initdb.d/01_users.sql
      - ./database/02_leagues.sql:/docker-entrypoint-initdb.d/02_leagues.sql
      - ./database/03_tx.sql:/docker-entrypoint-initdb.d/03_tx.sql
      - ./database/04_roster_stat.sql:/docker-entrypoint-initdb.d/04_roster_stat.sql

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    working_dir: "/go/src/gofant"
    command: ["/go/src/gofant/wait-for-pg.sh", "db", "go run main.go"]
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
